#server:
#  port: 25565

spring:
  cloud:
    gcp:
      storage:
        credentials:
          location: ${LOCATION}
        project-id: ${PROJECT_ID}
        bucket: ${BUCKET}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    p6spy:
      enable-logging: true
      # com.p6spy.engine.spy.appender.MultiLineFormat 사용 (SingleLineFormat 대신)
      multiline: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
#        format_sql: true
#    show-sql: true

    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mvc:
    async:
      request-timeout: -1

#logging:
#  level:
#    root: debug


jwt:
  secret: flature!@#